#include <stdio.h>
#include "../diksamc.h"


char *st_diksam_lang_dkh_text[] = {
	"void print(string str);\n",
	"void println(string str) {\n",
	"    print(str + \"\\n\");\n",
	"}\n",
	"\n",
	"class StackTrace {\n",
	"    int line_number;\n",
	"    string file_name;\n",
	"    string function_name;\n",
	"}\n",
	"\n",
	"abstract public class Exception {\n",
	"    public string message;\n",
	"    public StackTrace[] stack_trace;\n",
	"    \n",
	"    public void print_stack_trace() {\n",
	"        int i;\n",
	"        println(\"Exception occured. \" + this.message);\n",
	"        for (i = 0; i < this.stack_trace.size(); i++) {\n",
	"            println(\"\\tat \" \n",
	"                + this.stack_trace[i].function_name\n",
	"                + \"(\" + this.stack_trace[i].file_name \n",
	"                + \":\" + this.stack_trace[i].line_number \n",
	"                + \")\");\n",
	"        }\n",
	"    }\n",
	"\n",
	"    public virtual constructor init() {\n",
	"        this.stack_trace = new StackTrace[0];\n",
	"    }\n",
	"}\n",
	"\n",
	"abstract public class BugException : Exception {\n",
	"\n",
	"}\n",
	"\n",
	"abstract public class RuntimeException : Exception {\n",
	"\n",
	"}\n",
	"\n",
	"abstract public class ApplicationException : Exception {\n",
	"\n",
	"}\n",
	"\n",
	"public class NullPointerException : BugException {\n",
	"\n",
	"}\n",
	"\n",
	"public class ArrayIndexOutOfBoundsException : BugException {\n",
	"\n",
	"}\n",
	"\n",
	"public class StringIndexOutOfBoundsException : BugException {\n",
	"\n",
	"}\n",
	"\n",
	"public class DivisionByZeroException : RuntimeException {\n",
	"\n",
	"}\n",
	"\n",
	"public class MultibyteCharacterConvertionException : RuntimeException {\n",
	"\n",
	"}\n",
	"\n",
	"public class ClassCastException : BugException {\n",
	"\n",
	"}\n",
	"\n",
	"public class NumberFormatException : ApplicationException {\n",
	"\n",
	"}\n",
	NULL
};
char *st_diksam_lang_dkm_text[] = {
	"require diksam.lang;\n",
	"\n",
	"void fprintf(string file) {\n",
	"\n",
	"}\n",
	NULL
};
char *st_diksam_math_dkh_text[] = {
	"double fabs(double z);\n",
	"\n",
	"double pow(double z, double x);\n",
	"\n",
	"double fmod(double number, double divisor);\n",
	"\n",
	"double ceil(double z);\n",
	"\n",
	"double floor(double z);\n",
	"\n",
	"double sqrt(double z);\n",
	"\n",
	"double exp(double z);\n",
	"\n",
	"double log10(double z);\n",
	"\n",
	"double log(double z);\n",
	"\n",
	"double sin(double radian);\n",
	"\n",
	"double cos(double radian);\n",
	"\n",
	"double tan(double radian);\n",
	"\n",
	"double asin(double arg);\n",
	"\n",
	"double acos(double arg);\n",
	"\n",
	"double atan(double arg);\n",
	"\n",
	"double atan2(double num, double arg);\n",
	"\n",
	"double sinh(double value);\n",
	"\n",
	"double cosh(double value);\n",
	"\n",
	"double tanh(double value);\n",
	NULL
};

BuiltinScript dkc_builtin_script[] = {
	{"diksam.lang", DKH_SOURCE, st_diksam_lang_dkh_text},
	{"diksam.lang", DKM_SOURCE, st_diksam_lang_dkm_text},
	{"diksam.math", DKH_SOURCE, st_diksam_math_dkh_text},
	{NULL, DKM_SOURCE, NULL}
};
