//
// Created by sulvto on 18-6-18.
//
#include "diksamc.h"

ErrorDefinition dkc_error_message_format[] = {
		{"dummy"},
		{"PARSE_ERR"},
		{"CHARACTER_INVALID"},
		{"FUNCTION_MULTIPLE_DEFINE"},
		{"BAD_MULTIBYTE_CHARACTER"},
		{"LABEL_NOT_FOUND"},
		{"PACKAGE_NAME_TOO_LONG"},
		{"REQUIRE_DUPLICATE"},
		{"REQUIRE_FILE_NOT_FOUND"},
		{"REQUIRE_ITSELF"},
		{"ABSTRACT_MULTIPLE_SPECIFIED"},
		{"ACCESS_MODIFIER_MULTIPLE_SPECIFIED"},
		{"OVERRIDE_MODIFIER_MULTIPLE_SPECIFIED"},
		{"VIRTUAL_MODIFIER_MULTIPLE_SPECIFIED"},
		{"ABSTRACT_METHOD_HAS_BODY"},
		{"CONCRETE_METHOD_HAS_NO_BODY"},
		{"RENAME_HAS_NO_PACKAGED_NAME"},
		{"EOF_IN_C_COMMENT"},
		{"EOF_IN_STRING_LITERAL"},
		{"TOO_LONG_CHARACTER_LITERAL"},
		{"dummy"}
};
